spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gocredit
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
